spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: ${GALLERY_DATASOURCE_URL}
    username: ${GALLERY_DATASOURCE_USER}
    password: ${GALLERY_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

s3:
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  main-bucket-name: ${MAIN_S3_BUCKET}